### ISSUE TITLE
Supression of "ComposeModifierMissing" doesn't seem to work

### ISSUE THREAD

**Issue by raamcosta** [slackhq/compose-lints#137]
First of all, thank you for keeping this up, our team will benefit a lot from this.

However, while trying to add it to the project, I found that Suppress / SuppressLint doesn't work, at least with "ComposeModifierMissing", but I'm guessing possibly more/all.

**version** 1.2.0
**agp** 8.0.2
**lintapi** 31.0.2 (we also have a module with internal lints, not sure if this could matter)
**AS** Android Studio Flamingo | 2022.2.1 Patch 2

I wouldn't want to suppress this module-wide, but let me know if there's another way to suppress it case by case.

Let me know if I can help in any way.

**Comment by ZacSweers** [comment]
This is a known issue with lint suppressions on composable functions

A workaround @alexvanyo suggested elsewhere

> If you want a workaround `// noinspection ComposeModifierMissing` might work, I’ve gotten that to work with `ComposeModifierWithoutDefault` when `@Suppress` and `@SuppressLint` failed

**Comment by ZacSweers** [comment]
I'm closing this as this isn't an issue with this project. Please file an issue on Android Studio
