### ISSUE TITLE
Documentation displaying incorrect rule id

### ISSUE THREAD

**Issue by joeMalebe** [slackhq/compose-lints#169]
On the rules documentation under [Do not emit content and return a result](https://slackhq.github.io/compose-lints/rules/#do-not-emit-content-and-return-a-result:~:text=Related%20rule%3A%20ComposeMutableParameters-,Do%20not%20emit%20content%20and%20return%20a%20result,%C2%B6,-Composable%20functions%20should) the related rule points to ComposeMultipleContentEmitters. Should this be ComposeContentEmitterReturningValues rather.
<img width="839" alt="Screenshot 2023-09-12 at 14 29 44" src="https://github.com/slackhq/compose-lints/assets/17140850/86ed9116-196d-4942-b1d3-f8ab0971f371">

**Comment by ZacSweers** [comment]
Ah yeah good catch. Want to send a PR?
