### ISSUE TITLE
Usage of `Modifier.composed { }` is no longer recommended

### ISSUE THREAD

**Issue by migos** [slackhq/compose-lints#233]
The `ComposeComposableModifier` rule suggests the usage of `Modifier.composed { }` which is no longer recommended according to the Android developer documentation

Links:
* Android developers documentation: https://developer.android.com/jetpack/compose/custom-modifiers#create_a_custom_modifier_using_a_composable_modifier_factory
* `ComposeComposableModifier` rule: https://github.com/slackhq/compose-lints/blob/main/compose-lint-checks/src/main/java/slack/lint/compose/ModifierComposableDetector.kt

**Comment by ZacSweers** [comment]
Already done in #204, just not yet released
