### ISSUE TITLE
Cannot suppress ComposeViewModelInjection

### ISSUE THREAD

**Issue by ansman** [slackhq/compose-lints#241]
We have some code that looks like this:
```kotlin
@Composable
fun rememberStuff(): Stuff {
    val vm = viewModel<StuffViewModel>()
    remember { vm.createStuff() }
```

This gives is a lint error. And adding `@Suppress("ComposeViewModelInjection")` or `@SuppressLint("ComposeViewModelInjection")` does not work. Adding `// noinspection ComposeViewModelInjection` works however.

**Comment by ZacSweers** [comment]
See #57
