### ISSUE TITLE
Decide on a target lint version

### ISSUE THREAD

**Issue by ZacSweers** [slackhq/compose-lints#3]
In our main slack lints repo, we target the latest lint APIs because AGP allows using newer versions of lint, but that may be too opinionated for this library. We could instead just target latest stable lint APIs. With this also comes setting Kotlin language/api versions.

**Comment by ZacSweers** [comment]
I'm thinking for maximum portability, we should target latest AGP stable but (best-effort) ensure _forward_ compatibility by running tests against latest. We did this in the past with the slack lints repo with good success. Thoughts? @chrisbanes @mrmans0n @kierse

**Comment by chrisbanes** [comment]
Yeah, latest stable AGP seems like the safest option. We could forward fix with specially tagged releases.

**Comment by ZacSweers** [comment]
Resolved in 03ec9bc78031f4988e21ca8e76a98f02b34f127a. Accidentally pushed to main instead of a branch 🤦, but can revert and PR if you want!
