### ISSUE TITLE
404 For https://slackhq.github.io/compose-lints

### ISSUE THREAD

**Issue by commonsguy** [slackhq/compose-lints#35]
The project README links to https://slackhq.github.io/compose-lints, but that results in a 404.

**Comment by ZacSweers** [comment]
Apologies! We haven't deployed the site yet as we haven't released it on central yet (new repo). 

In the meantime you can take a look at [index.md](https://github.com/slackhq/compose-lints/blob/main/docs/index.md) and [rules.md](https://github.com/slackhq/compose-lints/blob/main/docs/rules.md)

**Comment by commonsguy** [comment]
No worries! With these sorts of broken links, it's not always clear to me if I'm too early or if something broke in a deploy process and the link should be working. I tend to report them just in case of the latter scenario.

I look forward to the release, and thanks (slightly in advance) for publishing it!

**Comment by ZacSweers** [comment]
Published!
