### ISSUE TITLE
And lint rule for "lifecycle expectations for slot parameters"

### ISSUE THREAD

**Issue by alexvanyo** [slackhq/compose-lints#367]
Duplicated from upstream issue: https://issuetracker.google.com/348654567

The Composable API guidelines specify the "Lifecycle expectations for slot parameters" here: https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-component-api-guidelines.md#lifecycle-expectations-for-slot-parameters

It should be possible to make a general lint rule enforcing this requirement, by checking that any slot parameter passed to a Composable is called in at most 1 location in the source code for the component.

If the slot parameter is called in 2 or more locations, then when the location changes, the internal state of the slot will be lost, which is generally unexpected behavior and can lead to loss of state.

(being called in 0 locations means that the parameter is unused, which should be handled by any unused parameter lint checks instead).

**Comment by ZacSweers** [comment]
PR welcome!
