### ISSUE TITLE
Deprecated rule `ComposeComposableModifier` ("Don't use `@Composable` builder functions for modifiers")

### ISSUE THREAD

**Issue by svenjacobs** [slackhq/compose-lints#369]
When creating a custom composable `Modifier`, the rule [ComposeComposableModifier](https://slackhq.github.io/compose-lints/rules/#avoid-modifier-extension-factory-functions) is applied. However this is now [officially permitted by Google](https://developer.android.com/develop/ui/compose/custom-modifiers#create_a_custom_modifier_using_a_composable_modifier_factory) since `composed {}` is no longer recommended.

**Comment by ZacSweers** [comment]
PR welcome to update this rule or remove it (whichever is more appropriate)

**Comment by ZacSweers** [comment]
Resolved by #378
