### ISSUE TITLE
Versions 1.4.1 and 1.4.0 require update to Android Gradle Plugin 8.7

### ISSUE THREAD

**Issue by dannybduval** [slackhq/compose-lints#421]
When trying to test out the new version 1.4.0 and 1.4.1, it appears that the change to [Lint 8.7](https://github.com/slackhq/compose-lints/compare/1.3.1...1.4.0#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87dfR12) requires updating the Android Gradle Plugin to 8.7.

I do have a sample project that shows this - https://github.com/dannybduval/SlackLint. It is just the sample empty activity project that Android Studio Koala produces (mainly because the preview in it violates the Slack Compose Lint rule of `@Preview` not being marked as private).

The project has 4 different branches that can show the outcomes of the following scenarios:

| AGP Version     | Gradle Version   | Slack Compose Lint Version  |  Lint outcome           |
| --------            | -------                 | -------                                     | -------                      |
| 8.3.2                 | 8.4                        |  1.3.1                                        | Failed (expected)     |
| 8.3.2                 | 8.4                        |  1.4.1                                        | Passed (should fail) |
| 8.6.1                 | 8.7                         |  1.4.1                                        | Passed (should fail) |
| 8.7.0                 | 8.9                         |  1.4.1                                        | Failed (expected)     |

**Comment by ZacSweers** [comment]
This is intended behavior and [documented in the release notes](https://github.com/slackhq/compose-lints/blob/main/CHANGELOG.md?plain=1#L33).

It also doesn't require AGP 8.7 specifically, just lint API 8.7. You can [update lint independently from AGP](https://googlesamples.github.io/android-custom-lint-rules/usage/newer-lint.md.html) if you don't want to update to AGP 8.7 yet.

**Comment by dannybduval** [comment]
Gotcha, wasn't sure if that was intended since it still worked as expected with 8.6.1 and that it's not clear that minApi was intended to mean lint. Thanks for the clarification.
