### ISSUE TITLE
Improve mutable parameters message

### ISSUE THREAD

**Issue by ZacSweers** [slackhq/compose-lints#48]
Feels like we could improve this a few ways

- Specify which parameter is mutable
- Should stable parameters be legal? i.e. like the `SnapshotStateList` here
- Is the linked rule correct?

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/1361086/217985154-98186076-7578-4e63-9538-beb4ec4dbba1.png">

**Comment by ZacSweers** [comment]
Actually I see `SnapshotStateList` is explicitly targeted. @chrisbanes @mrmans0n curious for more details!

**Comment by chrisbanes** [comment]
Hmm, I don't remember tbh. `SnapshotStateList` shouldn't be targeted as it's stable

**Comment by ZacSweers** [comment]
I'll remove those for now then 👍
