### ISSUE TITLE
Provide jar file to be used with detekt plugin in IntelliJ Android Studio

### ISSUE THREAD

**Issue by caikovsky** [slackhq/compose-lints#87]
In the old repo I noticed there's a way of downloading the releases in `jar` format so we could integrate it with `detekt` plugin in AS. Just wondering if there's a plan of doing that for this updated repo!

Also, amazing work guys. :)

**Comment by ZacSweers** [comment]
Lint works with the IDE out of the box, this isn't a detekt implementation. I think you're looking for https://github.com/mrmans0n/compose-rules
