### ISSUE TITLE
Lint to use collectAsStateWithLifecycle() instead of just collectAsState()

### ISSUE THREAD

**Issue by hrach** [slackhq/compose-lints#91]
Would this lint fit this repository?

**Comment by ZacSweers** [comment]
Can you expand more on its use? When should you use it vs collectAsState?

**Comment by hrach** [comment]
We think about it the other way around - considering why it shouldn't be used. 

Just today we experienced this:
- we have a main (single activity like) activity with a bottom navigation bar and nested graphs
- launching a login flow opens a different activity with own nav graph
- logging in in that activity
- change of the user state is propagated to the original activity where it is observed, even when the activity is stopped right now
